# Support for ROAD dataset will be updated soondataset_name : syncan
dataset_name : road
data_type : training # testing (override)
eval_type : original
root_dir: 'none' # Dummy value, will be assigned dynamically
data_dir: 'none' # Dummy value, will be assigned dynamically
train_data_dir: ../../../datasets/can-ids/road/signal_extractions/ambient
test_data_dir: ../../../datasets/can-ids/road/signal_extractions/attack
scaler_dir: ../scaler/
org_columns : ['Label', 'Time', 'ID',  Signal_1_of_ID,Signal_2_of_ID,Signal_3_of_ID,Signal_4_of_ID,Signal_5_of_ID,Signal_6_of_ID,Signal_7_of_ID,Signal_8_of_ID,Signal_9_of_ID,Signal_10_of_ID,Signal_11_of_ID,Signal_12_of_ID,Signal_13_of_ID,Signal_14_of_ID,Signal_15_of_ID,Signal_16_of_ID,Signal_17_of_ID,Signal_18_of_ID,Signal_19_of_ID,Signal_20_of_ID,Signal_21_of_ID,Signal_22_of_ID]
features : [Sig_7_of_ID_1413, 
Sig_5_of_ID_930, 
Sig_6_of_ID_1621, 
Sig_7_of_ID_186
, Sig_2_of_ID_692
, Sig_4_of_ID_1628
, Sig_2_of_ID_1255
, Sig_5_of_ID_1668
, Sig_4_of_ID_1760
, Sig_3_of_ID_1760
, Sig_6_of_ID_208
, Sig_2_of_ID_1760
, Sig_1_of_ID_1760
, Sig_2_of_ID_526
, Sig_4_of_ID_1176
, Sig_6_of_ID_167
, Sig_3_of_ID_208
, Sig_14_of_ID_1455
, Sig_1_of_ID_661
, Sig_1_of_ID_192
, Sig_1_of_ID_1227]

num_signals: 21
per_of_samples: 1.00 # <= 1.00, 1.00 means evaluation on 100% of data points
max_epoch: 100

time_steps: [50] # For complete evaluation use [25, 50, 75, 100]
time_step: 50 # Dummy value, will be assigned dynamically

sampling_periods: [1, 5, 10] # For complete evaluation use [1, 5, 10, 20, 50]
sampling_period : 1 # Dummy value, will be assigned dynamically

window_step : -1 # Place holder (will be asigned dynamically) Can be set to higher value to speed up the valuation
window_step_train: 10 # Can be set to higher value to speed up the valuation
window_step_valid : 10 # Can be set to higher value to speed up the valuation
window_step_test : 10 #10 # Can be set to higher value to speed up the valuation


# For testing/evluation 
## (To generate the results)
loss_factors : [95]
time_factors : [99]
signal_factors : [90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 99.5, 99.99]

## (To generate complete grid search)
# loss_factors : [90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 99.5, 99.99]
# time_factors : [90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 99.5, 99.99]
# signal_factors : [90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 99.5, 99.99]


loss_factor : 95 # Dummy value, will be assigned dynamically
time_factor : 99 # Dummy value, will be assigned dynamically

attacks_dict : {
        'Flooding': 'test_flooding',
        'Suppress': 'test_suppress',
        'Plateau': 'test_plateau',
        'Continuous': 'test_continuous',
        'Playback': 'test_playback',
        }